"""
Quality / safety validation for generated cold emails.

validate_email() checks a generated email before it is allowed through SMTP.
If it fails, the caller regenerates ONCE with a stricter prompt; if the second
attempt fails, the lead is marked generation_failed and skipped (no send).
"""
import re

PLACEHOLDER_RE = re.compile(r"\{\{\s*|\[(name|company|email|link|url|subject|your|recipient)"
                            r"\]|Lorem ipsum|<insert|\[insert\b", re.I)
SPAM_CAPS_RE = re.compile(r"\b[A-Z]{4,}\b")          # long ALL-CAPS words
# Legit single abbreviations (e.g. "HVAC" in "a HVAC contractor in Dallas TX")
# must not kill an otherwise clean email. Only 2+ distinct ALL-CAPS words flag.
LEGIT_CAPS_WORDS = {"HVAC", "COVID", "HTTP", "HTTPS", "WWW"}
BANG_QUESTION = re.compile(r"(!{2,}|\?{2,})")
MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+)\]\((https?://[^)]+)\)")
AI_MENTION_RE = re.compile(r"\b(as an? ai|generated by ai|chatgpt|artificial intelligence|"
                           r"language model|llm)\b", re.I)
UNSUPPORTED_CLAIM = re.compile(r"\btestimonial\b|\bcase stud(y|ies)\b|\bproven results\b|"
                               r"\bROI\b|\bwe (increased|boosted|grew) \d|"
                               r"\bincrease(?:d)? sales by \d", re.I)
FORMAL = re.compile(r"\bdear (sir|madam|sir/madam|sir or madam)\b", re.I)
SPAMMY = re.compile(r"\bact now\b|\bbook .*call\b|\bschedule .*demo\b|"
                    r"\blimited (time )?offer\b|\bdon'?t miss (out|this)\b|"
                    r"\bhurry\b|100%\s*(guaranteed|free)", re.I)

REQUIRED_LINKS = [
    "https://www.linkedin.com/in/surya-kant-pandey-2a54b0298",
    "https://github.com/suryaexists2",
]
REQUIRED_SIGNATURE = "best,\nsurya"


def _normalize(s):
    return re.sub(r"\s+", " ", (s or "")).strip().lower()


def _duplicate_paragraphs(body):
    paras = [re.sub(r"\s+", " ", p.strip()) for p in (body or "").split("\n\n")
             if p.strip()]
    seen = {}
    dupes = []
    for p in paras:
        if len(p) > 40:
            seen[p] = seen.get(p, 0) + 1
            if seen[p] > 1:
                dupes.append(p[:40])
    return dupes


def validate_email(subject, body, recipient):
    """Return (ok: bool, reasons: list[str])."""
    reasons = []
    subj = (subject or "").strip()
    body_t = (body or "").strip()
    recip = (recipient or "").strip()

    if not subj:
        reasons.append("subject missing")
    elif len(subj) > 90:
        reasons.append("subject too long")
    if not body_t:
        reasons.append("body missing")
    if not recip or "@" not in recip:
        reasons.append("recipient email missing/invalid")

    if body_t:
        wc = len(body_t.split())
        if wc < 40:
            reasons.append(f"body too short ({wc} words)")
        elif wc > 260:
            reasons.append(f"body too long ({wc} words)")

    if PLACEHOLDER_RE.search(subj + " " + body_t):
        reasons.append("placeholder text found ([Name]/[Company])")
    if FORMAL.search(body_t):
        reasons.append("formal 'Dear Sir/Madam' style")
    if BANG_QUESTION.search(body_t):
        reasons.append("excessive !!! / ???")
    caps_words = set(SPAM_CAPS_RE.findall(body_t or "")) - LEGIT_CAPS_WORDS
    if len(caps_words) >= 2:
        reasons.append("suspicious ALL-CAPS words")
    if AI_MENTION_RE.search(body_t):
        reasons.append("mentions AI/Gemini generation")
    if UNSUPPORTED_CLAIM.search(body_t):
        reasons.append("unsupported claim (testimonial/case study/ROI)")
    if SPAMMY.search(body_t):
        reasons.append("spammy marketing language")

    if _duplicate_paragraphs(body_t):
        reasons.append("duplicate paragraphs")

    # CTA + signature + links must be present (structure requirement)
    nb = _normalize(body_t)
    if "reply to this email" not in nb:
        reasons.append("missing reply-based CTA")
    if "best," not in nb or "surya" not in nb:
        reasons.append("missing 'Best, Surya' signature")
    for link in REQUIRED_LINKS:
        if link not in body_t:
            reasons.append("missing required link (LinkedIn/GitHub)")

    return (len(reasons) == 0, reasons)
